import Head from "next/head";

export default function Home() {
  return (
    <div className={`justify-center items-center w-full min-h-screen`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            @import url('https://fonts.googleapis.com/css2?family=Nunito&display=swap');
          `}
        </style>
      </Head>
      <h1 className="text-[60px] text-center font-bold underline text-red-200 py-12">
        Hello World!
      </h1>
    </div>
  );
}
